### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by psuedolet** [nornagon/cdda-guide#70]
Search returns 0 results, even for terms that should have results (e.g. 'zombie'). 

Console output in FF:
```
Uncaught (in promise) TypeError: d is undefined        ItemSymbol.svelte:1:17
    h ItemSymbol.svelte:1
    update ItemSymbol.svelte:1
    Q index.mjs:1485
    Qt colors.ts:269
    Hh SearchResults.svelte:80
    Gh SearchResults.svelte:75
    Ph SearchResults.svelte:72
    Wh SearchResults.svelte:71
    Q index.mjs:1489
    Yh SearchResults.svelte:1
    dg App.svelte:150
    p App.svelte:162
    p App.svelte:142
    P index.mjs:764
    j index.mjs:732

```

Console output in Chrome:
```
ItemSymbol.svelte:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'byId')
    at h (ItemSymbol.svelte:1:18)
    at Object.Zt.t.$$.update (ItemSymbol.svelte:1:18)
    at Q (index.mjs:1485:8)
    at new Qt (colors.ts:269:80)
    at Hh (SearchResults.svelte:80:35)
    at Gh (SearchResults.svelte:75:9)
    at Array.Ph (SearchResults.svelte:72:5)
    at Wh (SearchResults.svelte:71:6)
    at Q (index.mjs:1489:37)
    at new Yh (SearchResults.svelte:1:18)
    at dg (App.svelte:150:10)
    at Object.p (App.svelte:162:11)
    at Object.p (App.svelte:142:21)
    at P (index.mjs:764:36)
    at j (index.mjs:732:13)
```  

![image](https://user-images.githubusercontent.com/29447613/166346311-7af25662-97cb-4bbb-b711-9ca79052bea2.png)

**Comment by nornagon** [comment]
Thanks for letting me know, this should be fixed now. I'm surprised the tests didn't catch that! Will have to poke around to figure out what happened.
